export const recentTrips = [
    {
        id: 1,
        destination: "Shimla, Himachal Pradesh",
        date: "Dec 15-22, 2024",
        planType: "family",
        image: "/api/placeholder/300/200",
        arViewed: true,
        hasAR: true,
        has3D: true,
        hasVR: false,
        budget: "₹65,000",
        participants: 4,
    },
    {
        id: 2,
        destination: "Goa, India",
        date: "Nov 8-15, 2024",
        planType: "solo",
        image: "/api/placeholder/300/200",
        rating: 5,
        hasAR: true,
        has3D: true,
        hasVR: true,
        budget: "₹55,000",
        participants: 1,
    },
    {
        id: 3,
        destination: "Jaipur, Rajasthan",
        date: "Oct 20-25, 2024",
        planType: "couple",
        image: "/api/placeholder/300/200",
        rating: 4,
        hasAR: true,
        has3D: false,
        hasVR: true,
        budget: "₹48,000",
        participants: 2,
    },

];